services:
  - type: web
    name: call-center-api
    env: python
    runtime: python-3.11
    buildCommand: pip install -r backend/app/requirements.txt
    startCommand: cd backend/app && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ALLOWED_ORIGINS
        value: "https://call-center-sooty.vercel.app/"